/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/cliparser-extensions-v11.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.iosxr.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module cliparser-extensions-v11.yang */
public class cliparserExtensionsV11 extends ConfNamespace {

    public static final long serialVersionUID = 303487303L;

    public static final int hash = 303487303;
    public int hash() {
        return cliparserExtensionsV11.hash;
    }

    public static final String id = "_cisco-iosxr-cli-7.61:cisco-iosxr-cli-7.61#http://tail-f.com/ned/cliparser_v11";
    public String id() {
        return cliparserExtensionsV11.id;
    }

    public static final String uri = "_cisco-iosxr-cli-7.61:cisco-iosxr-cli-7.61#http://tail-f.com/ned/cliparser_v11";
    public String uri() {
        return cliparserExtensionsV11.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(cliparserExtensionsV11.uri);
    }

    public static final String prefix = "cli";
    public String prefix() {
        return cliparserExtensionsV11.prefix;
    }

    public cliparserExtensionsV11() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
