ned-name=extreme-xos
ned-platform-name=ExtremeXOS
ned-version=1.5.5
ned-date=2024-08-29
ned-id=extreme-xos-id:extreme-xos
ned-module=tailf-ned-extreme-xos
ned-module-ns=http://tail-f.com/ned/extreme-xos
ned-meta-prefix=extreme-xos-meta
ned-stats-module=tailf-ned-extreme-xos-stats
ned-stats-module-ns=http://tail-f.com/ned/extreme-xos/stats
legacy-serial-tag=extreme-xos-serial-number
parser.config.matchModeAsCompact=false
ned.capability.wantRevertDiff=true
ned.capability.defaultsMode=report-all
ned.capability.showStatsPath=false
parser.config.matchRelaxed=true
parser.config.matchPartialTokens=true
parser.config.matchEnumsPartial=true
parser.matchEnumsIgnoreCase=true
