MAIN_YANG_MODULE = tailf-ned-extreme-xos.yang
PACKAGE_NAME=extremexos

# If the NED supports extra stats models in addition to the
# regular one, then add them to EXTRA_YANG_STATS_MODULES.
# Example: ietf-interfaces.yang ietf-ip.yang
EXTRA_YANG_STATS_MODULES=

# Set to yes if the config data models shall be augmented
# into the NSO live-status as well.
BUILD_CONFIG_MODELS_AS_STATS=no

all: all_cli

include nedcom.mk

